apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      component: server
  template:
    metadata: 
      labels:
        component: server
    spec:
      containers:
        - name: server
          image: porzechowski/multi-server
          ports:
            - containerPort: 5000
          resources:
              requests:
                memory: "16Mi"
                cpu: "100m"
              limits:
                memory: "48Mi"
                cpu: "500m"    
